In [2]:
print("AI Journey Start 🚀")


AI Journey Start 🚀


In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # addition
print(a * b)   # multiplication


[5 7 9]
[ 4 10 18]


In [4]:
import numpy as npp
a1= npp.array([1, 2, 3])
print(a1)

[1 2 3]


In [3]:
#indexing and slicing
import numpy as npp
a1= npp.array([1, 2, 3])
print(a1)
print('First element:', a1[0])  # first element
print('Last element:', a1[-1])  # last element
print('Slicing:', a1[0:2])  # slicing

[1 2 3]
First element: 1
Last element: 3
Slicing: [1 2]


In [7]:
# array math
import numpy as npp
a1 = npp.array([1, 2, 3])
a2 = npp.array([4, 5, 6])
print('Adding 12 to a1:', a1 + 12)  # addition
print('Multiplying a1 by 2:', a1 * 2)  # multiplication
print('Adding a1 and a2:', a1 + a2)  # element-wise addition

Adding 12 to a1: [13 14 15]
Multiplying a1 by 2: [2 4 6]
Adding a1 and a2: [5 7 9]


In [1]:
import numpy as np
prices_usd = np.array([10, 20, 30])
indian_rupees = prices_usd * 83
print(indian_rupees)


[ 830 1660 2490]


In [3]:
#1D to 2D  and 3D array
import numpy as np
a1=np.arange(24)
a2=a1.reshape(6,4)
a3=a1.reshape(2,3,4)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [8]:
#indexing and slicing in 2D and 3D array
import numpy as np
a1=np.arange(24).reshape(6,4)
a2=np.arange(24).reshape(2,3,4)
#2D array indexing and slicing
print('Element at row 1, column 2:', a1[1, 2])  # element at row 1, column 2
print('Row 1:', a1[1])  # row 1
print('Column 2:', a1[:, 2])  # column 2


Element at row 1, column 2: 6
Row 1: [4 5 6 7]
Column 2: [ 2  6 10 14 18 22]


In [10]:
#3D array indexing and slicing
print('3D Array a2:\n', a2)
print('Element at block 0, row 1, column 2:', a2[0, 1, 2])  # element at block 0, row 1, column 2
print('Block 0:', a2[0])  # block 0
print('Row 1 across all blocks:', a2[:, 1, :])  # row 1 across all blocks
print('Column 2 across all blocks:', a2[:, :, 2])  # column 2 across all blocks
print('Slicing block 0, rows 0-1, columns 1-3:', a2[0, 0:2, 1:4])  # slicing block 0, rows 0-1, columns 1-3

3D Array a2:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Element at block 0, row 1, column 2: 6
Block 0: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row 1 across all blocks: [[ 4  5  6  7]
 [16 17 18 19]]
Column 2 across all blocks: [[ 2  6 10]
 [14 18 22]]
Slicing block 0, rows 0-1, columns 1-3: [[1 2 3]
 [5 6 7]]


In [1]:
#Boolean filtering 1D 2D and 3D array
import numpy as np
a1=np.arange(24)
a2=np.arange(24).reshape(6,4)
a3=np.arange(24).reshape(2,3,4)
#Boolean filtering in 1D array
print('1D Array a1:\n', a1)
print('Elements greater than 10:', a1 > 10)  # elements greater than 10
#Boolean filtering in 2D array
print('2D Array a2:\n', a2)
print('Elements greater than 10:\n', a2[a2 > 10])  # elements greater than 10
#Boolean filtering in 3D array
print('3D Array a3:\n', a3)
print('Elements greater than 10:\n', a3 > 10)  # elements greater than 10


1D Array a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Elements greater than 10: [False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True]
2D Array a2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Elements greater than 10:
 [11 12 13 14 15 16 17 18 19 20 21 22 23]
3D Array a3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Elements greater than 10:
 [[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [14]:
#aggregation /statistics in 1D 2D and 3D array
import numpy as np
a1=np.arange(24)
a2=np.arange(24).reshape(6,4)
a3=np.arange(24).reshape(2,3,4)
#Aggregation in 1D array
print('1D Array a1:\n', a1)
print('Sum:', np.sum(a1))
print('Mean:', np.mean(a1))
print('Standard Deviation:', np.std(a1))
print('Variance:', np.var(a1))
#Aggregation in 2D array
print('2D Array a2:\n', a2)
print('Sum:', np.sum(a2))
print('Mean:', np.mean(a2))
print('Standard Deviation:', np.std(a2))
print('Variance:', np.var(a2))
#Aggregation in 3D array
print('3D Array a3:\n', a3)
print('Sum:', np.sum(a3))
print('Mean:', np.mean(a3))
print('Standard Deviation:', np.std(a3))
print('Variance:', np.var(a3))

1D Array a1:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
Sum: 276
Mean: 11.5
Standard Deviation: 6.922186552431729
Variance: 47.916666666666664
2D Array a2:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Sum: 276
Mean: 11.5
Standard Deviation: 6.922186552431729
Variance: 47.916666666666664
3D Array a3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Sum: 276
Mean: 11.5
Standard Deviation: 6.922186552431729
Variance: 47.916666666666664


In [4]:
import numpy as np
a1=np.arange(24)
a2=np.arange(24).reshape(6,4)
a3=np.arange(24).reshape(2,3,4)
#resize
a1.resize(8)  # resize 1D array to length 8
print('Resized 1D Array a1:\n', a1)
a2.resize(4, 6)  # resize 2D array to shape (4, 6)
print('Resized 2D Array a2:\n', a2)
#add 2d and 3d array
a2_reshaped = a2.reshape(2, 3, 4)  # reshape a2 to match a3's shape
result = a2_reshaped + a3  # element-wise addition
print('Result of Adding 2D and 3D Arrays:\n', result)

Resized 1D Array a1:
 [0 1 2 3 4 5 6 7]
Resized 2D Array a2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
Result of Adding 2D and 3D Arrays:
 [[[ 0  2  4  6]
  [ 8 10 12 14]
  [16 18 20 22]]

 [[24 26 28 30]
  [32 34 36 38]
  [40 42 44 46]]]
